### ISSUE TITLE
negative values of -log10(Adj. p)

### ISSUE THREAD

**Issue by zh-zhang1984** [xmc811/Scillus#12]
Hi, thank you for your excellent package and I really enjoying many downstream analysis with the package. However, I found in the GSEA plot, the -log10(Adj. p) values can take negative values which is not feasible to me. p value is always less than 1, and -log10(p) should always > 0.

**Comment by xmc811** [comment]
Thank you for using the package.

The labeling text here is inaccurate. The color actually indicates -log10(Adjusted p-value) * the sign of the normalized enrichment score (NES) of GSEA. The sign will be `1` if the pathway is up-regulated, and `-1` if it's down-regulated. That's why you see negative values (blue color ones) in the plot. The code snippet below shows the code that calculates the color value.

https://github.com/xmc811/Scillus/blob/4e7884d29ba8997669ff848983257cb0cf37a318/R/visualization.R#L590

One quick solution is to try overriding the legend text. Example:
```
plot_GSEA(gsea_res, p_cutoff = 0.1, colors = c("#0570b0", "grey", "#d7301f")) +
        labs(color = "Your Favourite Labeling Text")
```

I'll try to correct the bug if I'll work on the next version.

**Comment by zh-zhang1984** [comment]
Thank you for your clarification.
